name: rive_demo
description: A rive demo app for the Flutter London event.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.11.17
  sensors_plus: ^3.1.0
  transparent_pointer: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # Used for generating localizations code
  generate: true
  assets:
    - assets/
